use crate::QueryOutput;
use crate::app::types::QueryEditorResizeDrag;
use crate::model::settings::HistoryViewMode;
use iced::keyboard;
use iced_code_editor::{CodeEditor, Message as EditorMessage};
use std::collections::{HashMap, HashSet};
use std::sync::Arc;
use std::sync::atomic::AtomicBool;

#[derive(Debug, Clone)]
pub(crate) enum Message {
    ToggleHistoryPanel,
    HistoryViewModeSelected(HistoryViewMode),
    RelationsSelected(String),
    TablePageNext,
    TablePagePrev,
    TablePageFirst,
    TablePageLast,
    TableLastPageResolved(String, Result<QueryOutput, String>),
    HistorySelected(String),
    ClearQueryHistory,
    SaveCurrentQuery,
    SavedQuerySelected(String),
    DeleteSavedQuery(usize),
    CopySavedQuery(String),
    ClearSavedQueries,
    QueryEditorResizeDragStarted,
    QueryAction(EditorMessage),
    RunQuery,
    CancelQuery,
    ToggleStructureView,
    NewQuery,
    ClearResults,
    QueryScriptFinished(Result<Vec<QueryOutput>, String>),
    QueryFinished(Result<QueryOutput, String>),
    QuerySuggestionColumnsLoaded {
        table: String,
        result: Result<Vec<String>, String>,
    },
    InlineQuerySuggestionReady {
        request_id: u64,
        anchor: String,
        anchor_offset: usize,
        result: Result<String, String>,
    },
    CopyQueryError,
    QueryEditorCapturedKeyPressed(keyboard::Event),
    RunSelection,
    RunSelectionClipboardLoaded {
        original: Option<String>,
        fallback: Option<String>,
    },
    RunSelectionCopied {
        original: Option<String>,
        selection: Option<String>,
        fallback: Option<String>,
    },
    UndoQuery,
    RedoQuery,
    OpenQuerySuggestions,
    ApplyQuerySuggestion(usize),
    AcceptInlineQuerySuggestion,
    AcceptInlineQuerySuggestionWord,
    DismissInlineQuerySuggestion,
    FocusQueryEditorNow,
}

pub(crate) struct State {
    pub(crate) running: bool,
    pub(crate) cancel_flag: Option<Arc<AtomicBool>>,
    pub(crate) error: Option<String>,
    pub(crate) table_query: Option<String>,
    pub(crate) editable_query: Option<String>,
    pub(crate) table: Option<String>,
    pub(crate) history: Vec<String>,
    pub(crate) history_times: Vec<String>,
    pub(crate) history_panel_expanded: bool,
    pub(crate) history_view_mode: HistoryViewMode,
    pub(crate) undo_stack: Vec<String>,
    pub(crate) redo_stack: Vec<String>,
    pub(crate) suggestions_open: bool,
    pub(crate) suggestions: Vec<String>,
    pub(crate) suggestion_index: usize,
    pub(crate) editor_blurred: bool,
    pub(crate) editor_bounds: std::cell::Cell<iced::Rectangle>,
    pub(crate) inline_suggestion: Option<String>,
    pub(crate) inline_suggestion_cache: Option<(String, usize, String)>,
    pub(crate) inline_suggestion_loading: bool,
    pub(crate) inline_suggestion_request_id: u64,
    pub(crate) inline_suggestion_last_request_at: Option<std::time::Instant>,
    pub(crate) inline_suggestion_last_edit_at: Option<std::time::Instant>,
    pub(crate) inline_suggestion_pending: bool,
    pub(crate) editor_last_action_edited: bool,
    pub(crate) editor_pending_key_action: Option<EditorMessage>,
    pub(crate) editor_resize_drag: Option<QueryEditorResizeDrag>,
    pub(crate) suggestion_columns_cache: HashMap<String, Vec<String>>,
    pub(crate) suggestion_columns_loading: HashSet<String>,
    pub(crate) editor: CodeEditor,
    pub(crate) table_has_next_page: bool,
    pub(crate) last_query_was_table: bool,
}

impl State {
    pub(crate) fn new(editor: CodeEditor) -> Self {
        Self {
            running: false,
            cancel_flag: None,
            error: None,
            table_query: None,
            editable_query: None,
            table: None,
            history: Vec::new(),
            history_times: Vec::new(),
            history_panel_expanded: false,
            history_view_mode: HistoryViewMode::default(),
            undo_stack: Vec::new(),
            redo_stack: Vec::new(),
            suggestions_open: false,
            suggestions: Vec::new(),
            suggestion_index: 0,
            editor_blurred: false,
            editor_bounds: std::cell::Cell::new(iced::Rectangle::default()),
            inline_suggestion: None,
            inline_suggestion_cache: None,
            inline_suggestion_loading: false,
            inline_suggestion_request_id: 0,
            inline_suggestion_last_request_at: None,
            inline_suggestion_last_edit_at: None,
            inline_suggestion_pending: false,
            editor_last_action_edited: false,
            editor_pending_key_action: None,
            editor_resize_drag: None,
            suggestion_columns_cache: HashMap::new(),
            suggestion_columns_loading: HashSet::new(),
            editor,
            table_has_next_page: false,
            last_query_was_table: false,
        }
    }
}
