use crate::app::session::{ConnectionTab, DatabaseSessionState};
use crate::app::types::{FavoriteContextMenuState, FavoriteEditModalState};
use crate::constants::MYSQL_DEFAULT_PORT;
use crate::db::DatabasePool;
use crate::model::connection::{
    ConnectionInfo, ConnectionStore, DatabaseDriver, StoredConnection, TlsMode,
};
use iced::widget::scrollable;
use iced::{keyboard, mouse};
use sqlx::{MySqlPool, PgPool, SqlitePool};
use std::collections::HashMap;
use std::path::PathBuf;

#[derive(Debug, Clone)]
pub(crate) enum Message {
    DriverSelected(DatabaseDriver),
    ToggleDriverPicker,
    HostChanged(String),
    PortChanged(String),
    DatabaseChanged(String),
    UsernameChanged(String),
    PasswordChanged(String),
    TlsModeSelected(TlsMode),
    TlsCaCertPathChanged(String),
    TlsCaCertBrowsePath,
    TlsCaCertPicked(Option<PathBuf>),
    SqlitePathChanged(String),
    SqliteBrowsePath,
    SqliteCreatePath,
    SqliteFilePicked(Option<PathBuf>),
    SqliteCreatePicked(Option<PathBuf>),
    SqliteDatabaseCreated(Result<String, String>),
    AddFavorite,
    FavoriteSelected(usize),
    FavoriteDeleted(usize),
    FavoriteContextMenuRequested { index: usize },
    CloseFavoriteContextMenu,
    OpenFavoriteEditModal(usize),
    CloseFavoriteEditModal,
    FavoriteEditNameChanged(String),
    FavoriteEditTagsChanged(String),
    SaveFavoriteEdit,
    RecentSelected(usize),
    RecentDeleted(usize),
    ConnectionTabSelected(u64),
    ConnectionTabClosed(u64),
    Connect,
    SqliteConnected(Result<(SqlitePool, String), String>),
    Connected(Result<MySqlPool, String>),
    PostgresConnected(Result<PgPool, String>),
    Disconnect,
    RefreshTables,
    RefreshDatabases,
    RefreshDatabaseAndTables,
    TablesLoaded(Result<Vec<String>, String>),
    TableRowCountsLoaded(std::collections::HashMap<String, u64>),
    DatabasesLoaded(Result<Vec<String>, String>),
    DatabaseSelected(String),
    DatabaseSearchChanged(String),
    CopyConnectError,
    CopyConnectionStoreError,
    ConnectionTabsScrolled(scrollable::Viewport),
    ConnectionTabsWheelScrolled(mouse::ScrollDelta),
    LoginKeyPressed(keyboard::Event),
    OpenPostgresTerminal,
    ClosePostgresTerminal,
    PostgresTerminalEvent(iced_term::Event),
    ToggleDatabasePicker,
    ToggleConnectionPicker,
    CloseConnectionPicker,
    StartNewConnection,
    CloseDatabaseSwitcher,
}

pub(crate) struct State {
    pub(crate) current: ConnectionInfo,
    pub(crate) tabs: Vec<ConnectionTab>,
    pub(crate) active_tab_id: Option<u64>,
    pub(crate) next_tab_id: u64,
    pub(crate) favorites: Vec<StoredConnection>,
    pub(crate) recents: Vec<StoredConnection>,
    pub(crate) store_error: Option<String>,
    pub(crate) pool: Option<DatabasePool>,
    pub(crate) database_sessions: HashMap<String, DatabaseSessionState>,
    pub(crate) connected: bool,
    pub(crate) connecting: bool,
    pub(crate) loading_tables: bool,
    pub(crate) loading_databases: bool,
    pub(crate) favorite_context_menu: Option<FavoriteContextMenuState>,
    pub(crate) favorite_edit_modal: Option<FavoriteEditModalState>,
    pub(crate) connect_error: Option<String>,
    pub(crate) table_error: Option<String>,
    pub(crate) database_error: Option<String>,
    pub(crate) databases: Vec<String>,
    pub(crate) database_search: String,
    pub(crate) tabs_horizontal_viewport: Option<scrollable::Viewport>,
    pub(crate) driver_picker_open: bool,
    pub(crate) database_picker_open: bool,
    pub(crate) connection_picker_open: bool,
    pub(crate) more_options_open: bool,
    pub(crate) postgres_terminal_open: bool,
    pub(crate) postgres_terminal_title: String,
    pub(crate) postgres_terminal: Option<iced_term::Terminal>,
    pub(crate) postgres_terminal_pgpass: Option<tempfile::NamedTempFile>,
    pub(crate) next_postgres_terminal_id: u64,
}

impl State {
    pub(crate) fn new(store: ConnectionStore, store_error: Option<String>) -> Self {
        Self {
            current: ConnectionInfo {
                driver: DatabaseDriver::MySql,
                host: String::from("127.0.0.1"),
                port: MYSQL_DEFAULT_PORT.to_string(),
                database: String::new(),
                username: String::new(),
                password: String::new(),
                sqlite_path: String::new(),
                tls_mode: TlsMode::Prefer,
                tls_ca_cert_path: String::new(),
                tls_client_cert_path: String::new(),
                tls_client_key_path: String::new(),
            },
            tabs: Vec::new(),
            active_tab_id: None,
            next_tab_id: 1,
            favorites: store.favorites,
            recents: store.recents,
            store_error,
            pool: None,
            database_sessions: HashMap::new(),
            connected: false,
            connecting: false,
            loading_tables: false,
            loading_databases: false,
            favorite_context_menu: None,
            favorite_edit_modal: None,
            connect_error: None,
            table_error: None,
            database_error: None,
            databases: Vec::new(),
            database_search: String::new(),
            tabs_horizontal_viewport: None,
            driver_picker_open: false,
            database_picker_open: false,
            connection_picker_open: false,
            more_options_open: false,
            postgres_terminal_open: false,
            postgres_terminal_title: String::new(),
            postgres_terminal: None,
            postgres_terminal_pgpass: None,
            next_postgres_terminal_id: 1,
        }
    }
}
